// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function OpenFile():Promise<main.Result>;

export function SaveFile(arg1:string,arg2:string):Promise<main.Result>;

export function SaveFileAs(arg1:string,arg2:string):Promise<main.Result>;

export function WarningMessage(arg1:string,arg2:string):Promise<main.Result>;
