// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function OpenFile():Promise<main.File>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SaveFileAs(arg1:string,arg2:string):Promise<void>;
